spring.application.name=lms-backend
server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lms-project
spring.datasource.username=postgres
spring.datasource.password=[password]
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# 'update' will generate the tables automatically based on your entities
spring.jpa.hibernate.ddl-auto=update
# Specify PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
